#!/usr/bin/env python
# -*- coding: utf-8 -*-

xgb_libsvm_feature = [
    "account_age",
    "alignment_day",
    "alignment_day_of_week",
    "alignment_hour",
    "alignment_month",
    "alignment_year",
    "all_call_num",
    "avgerage_waiting_time_of_dialogue",
    "consult_type",
    "consult_type_CALL",
    "contain_education_or_promotion_key_word_in_dialogue",
    "contain_price_key_word_in_dialogue",
    "create_user",
    "delta_days_from_entryDate",
    "delta_time_of_create_time_and_operator_time",
    "dialogue_start_at",
    "duration_of_dialogue",
    "educationalBackground",
    "first_proj_id",
    "gender",
    "graduateSchool",
    "major",
    "marriageState",
    "message_opp_distribution_num",
    "message_opp_distribution_saturation",
    "message_opp_limit_num",
    "nationalEdu",
    "number_of_dialogue",
    "number_of_student_dialogue",
    "online_opp_distribution_num",
    "online_opp_distribution_saturation",
    "online_opp_limit_num",
    "opp_completed_rate",
    "opp_following_num",
    "opp_today_following_num",
    "oppor_source",
    "pastNday_advertiser_applied_ratio",
    "pastNday_advertiser_distribution_num",
    "pastNday_advertiser_order_num",
    "pastNday_applied_ratio_on_siteId",
    "pastNday_distribution_num_on_siteId",
    "pastNday_order_num_on_siteId",
    "past_n_days_acc_alignment_num",
    "past_n_days_acc_order_amount",
    "past_n_days_acc_order_avg_amount",
    "past_n_days_acc_order_num",
    "past_n_days_acc_order_rate",
    "posLevel",
    "promotion_type",
    "quantum_id",
    "race",
    "recycle_opp_distribution_num",
    "recycle_opp_distribution_saturation",
    "recycle_opp_limit_num",
    "residenceType",
    "search_key_word",
    "site_source",
    "student_cellphone_midnum",
    "student_dialogue_fenci",
    "timedelta_from",
    "today_unfollowed_num",
    "twice_consult",
    "valid_call_num",
    "不良信用记录",
    "优惠券",
    "保障方式",
    "关心的问题",
    "减免学费",
    "可学习时间",
    "咨询目的",
    "城市",
    "备注",
    "姓名",
    "学习基础",
    "学习方式",
    "学历提升目的",
    "工作地点",
    "工作多久",
    "平时时间",
    "年龄",
    "性别",
    "性格",
    "意向专业",
    "意向院校",
    "户籍归属",
    "擅长科目",
    "是否了解免联考政策",
    "期望毕业时长",
    "期望考证方式",
    "毕业时长",
    "目前学历",
    "目前状态",
    "目标学历",
    "选择数学英语免考专业"
]

feature_map_ignore_ls = ["consult", "age", "num", "dialogue", "entryDate", "time", "saturation", "ratio", "rate",
                         "amount", "siteId", "CALL", "GREATBEAR"]

merge_feature_ls = ["oppor_source", "dialogue_start_at", "create_user"]

message_feature = ["不良信用记录", "优惠券", "保障方式", "关心的问题",
                   "减免学费", "可学习时间", "咨询目的", "城市",
                   "备注", "姓名", "学习基础", "学习方式",
                   "学历提升目的", "工作地点", "工作多久", "平时时间",
                   "年龄", "性别", "性格", "意向专业",
                   "意向院校", "户籍归属", "擅长科目", "是否了解免联考政策",
                   "期望毕业时长", "期望考证方式", "毕业时长", "目前学历",
                   "目前状态", "目标学历", "选择数学英语免考专业"]

drop_feature = ["search_key_word"] + message_feature

xgb_extract_feature = [x for x in xgb_libsvm_feature if x not in drop_feature]